# Generated by Django 4.0.2 on 2022-02-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
