# Generated by Django 4.0.2 on 2022-02-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contract_date_updated_alter_event_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
