# Generated by Django 4.0.2 on 2022-02-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contract_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='payment_status'),
        ),
    ]
