# Generated by Django 4.0.2 on 2022-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comapny_name_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
